# Generated by Django 4.0.1 on 2023-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_remove_request_sub_quantity_pickup_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='coins',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
