# Generated by Django 4.0.1 on 2023-10-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_schedule_request_schedule_request_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_sub',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
