# Generated by Django 4.0.1 on 2023-10-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_request_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='PICKUPDRIVER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Myapp.pickupdriver'),
        ),
    ]
