# Generated by Django 4.0.1 on 2023-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_schedule_pickupdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=100)),
                ('ifsccode', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
